# Generated by Django 3.2.15 on 2023-04-14 18:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0060_auto_20230414_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(default=None, editable=False, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.location')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model')),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pretty_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '[Admin] Template Types',
                'db_table': 'template_types',
            },
        ),
        migrations.CreateModel(
            name='Template_Type_Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude_offset', models.FloatField()),
                ('longitude_offset', models.FloatField()),
                ('template_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template_type')),
            ],
            options={
                'verbose_name_plural': '[Admin] Template Type Locs',
                'db_table': 'template_type_locs',
            },
        ),
        migrations.CreateModel(
            name='Template_Type_Loc_Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_loc_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_loc_1', to='template.template_type_loc')),
                ('template_loc_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_loc_2', to='template.template_type_loc')),
            ],
            options={
                'verbose_name_plural': '[Admin] Template Type Loc Techs',
                'db_table': 'template_type_loc_techs',
            },
        ),
        migrations.CreateModel(
            name='Template_Type_Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pretty_name', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('default_value', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timeseries_enabled', models.BooleanField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('template_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template_type')),
            ],
            options={
                'verbose_name_plural': '[Admin] Template Type Variables',
                'db_table': 'template_type_variables',
            },
        ),
        migrations.CreateModel(
            name='Template_Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('raw_value', models.CharField(blank=True, max_length=200, null=True)),
                ('timeseries', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(default=None, editable=False, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template')),
                ('template_type_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template_type_variable')),
                ('timeseries_meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.timeseries_meta')),
            ],
            options={
                'verbose_name_plural': 'Template Variables',
                'db_table': 'template_variables',
            },
        ),
        migrations.CreateModel(
            name='Template_Type_Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('carrier_in', models.CharField(max_length=200)),
                ('carrier_out', models.CharField(blank=True, max_length=200, null=True)),
                ('abstract_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.abstract_tech')),
                ('template_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template_type')),
            ],
            options={
                'verbose_name_plural': '[Admin] Template Type Techs',
                'db_table': 'template_type_techs',
            },
        ),
        migrations.CreateModel(
            name='Template_Type_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation', models.CharField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter')),
                ('template_loc_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template_type_loc_tech')),
            ],
            options={
                'verbose_name_plural': '[Admin] Template Type Parameters',
                'db_table': 'template_type_parameters',
            },
        ),
        migrations.AddField(
            model_name='template_type_loc_tech',
            name='template_tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template_type_tech'),
        ),
        migrations.AddField(
            model_name='template_type_loc_tech',
            name='template_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template_type'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template_type'),
        ),
    ]
