# Generated by Django 3.2.15 on 2023-04-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_type_tech',
            name='carrier_in_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='template_type_tech',
            name='carrier_in_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='template_type_tech',
            name='carrier_out_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='template_type_tech',
            name='carrier_out_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='template_type_tech',
            name='carrier_ratios',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='template_type_tech',
            name='carrier_in',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
