# Generated by Django 3.2.23 on 2024-02-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_parameter_tags'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_type_variable',
            name='choices',
        ),
        migrations.AddField(
            model_name='template_type_variable',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RenameModel(
            old_name='Template_Type_Parameter',
            new_name='Template_Type_Loc_Tech_Param',
        ),
        migrations.AlterModelOptions(
            name='template_type_loc_tech_param',
            options={'verbose_name_plural': '[Admin] Template Type Loc Tech Parameters'},
        ),
        migrations.AlterModelTable(
            name='template_type_loc_tech_param',
            table='template_type_loc_tech_parameters',
        ),
        migrations.CreateModel(
            name='Template_Type_Tech_Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation', models.CharField(max_length=200)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parameter')),
                ('template_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template_type_tech')),
            ],
            options={
                'verbose_name_plural': '[Admin] Template Type Tech Parameters',
                'db_table': 'template_type_tech_params',
            },
        ),
    ]
