# Generated by Django 3.2.24 on 2024-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_auto_20240229_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_type_tech',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
