# Generated by Django 4.2.16 on 2025-09-15 02:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_alter_template_type_tech_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_type_loc_tech_param',
            name='dim',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='template_type_loc_tech_param',
            name='index',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='template_type_loc_tech_param',
            name='piecewise_dim',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='template_type_tech_param',
            name='dim',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='template_type_tech_param',
            name='index',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='template_type_tech_param',
            name='piecewise_dim',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
