# Generated by Django 2.1.4 on 2019-06-25 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_model_snapshot_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='snapshot_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Model'),
        ),
    ]
