# Generated by Django 2.1.4 on 2019-07-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190709_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc_tech_param',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tech_param',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
