# Generated by Django 2.1.4 on 2019-07-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190709_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_user',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
