# Generated by Django 2.1.4 on 2019-07-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190710_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='model',
        ),
        migrations.DeleteModel(
            name='Carrier',
        ),
    ]
