# Generated by Django 2.1.4 on 2019-08-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190730_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries_meta',
            name='is_uploading',
            field=models.BooleanField(default=False),
        ),
    ]
