# Generated by Django 2.1.4 on 2019-08-05 03:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseries',
            name='meta',
        ),
        migrations.AlterModelOptions(
            name='model_user',
            options={'ordering': ['user__user_profile__organization'], 'verbose_name_plural': '[0] Model Users'},
        ),
        migrations.RemoveField(
            model_name='timeseries_meta',
            name='is_uploading',
        ),
        migrations.AddField(
            model_name='timeseries_meta',
            name='file_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='Timeseries',
        ),
    ]
