# Generated by Django 2.1.4 on 2019-08-11 20:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190805_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=None),
        ),
    ]
