# Generated by Django 2.1.4 on 2019-08-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190811_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
