# Generated by Django 2.1.4 on 2019-08-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_run_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries_meta',
            name='original_filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
