# Generated by Django 2.1.4 on 2019-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_timeseries_meta_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries_meta',
            name='original_timestamp_col',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timeseries_meta',
            name='original_value_col',
            field=models.IntegerField(null=True),
        ),
    ]
