# Generated by Django 2.1.4 on 2019-08-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_run_message'),
        ('api', '0018_auto_20190819_1805'),
    ]

    operations = [
    ]
