# Generated by Django 2.1.4 on 2019-08-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20190826_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries_meta',
            name='is_uploading',
            field=models.BooleanField(default=False),
        ),
    ]
