# Generated by Django 2.1.4 on 2019-09-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190906_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='build_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='build_run', to='taskmeta.CeleryTask'),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_run', to='taskmeta.CeleryTask'),
        ),
    ]
