# Generated by Django 2.1.4 on 2019-10-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190909_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
