# Generated by Django 2.1.4 on 2019-11-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_model_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='run_parameter',
            name='can_evolve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scenario_param',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loc_tech_param',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tech_param',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
