# Generated by Django 2.1.4 on 2019-11-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20191106_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help_Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '[Admin] Help Guide',
                'db_table': 'help_guide',
            },
        ),
    ]
