# Generated by Django 2.1.4 on 2019-12-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_help_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_user',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
