# Generated by Django 2.1.4 on 2019-12-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_model_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries_meta',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timeseries_meta',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
