# Generated by Django 2.1.4 on 2019-12-27 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20191223_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='activation_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
