# Generated by Django 2.1.4 on 2020-01-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200108_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='is_expansion',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='is_linear',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
