# Generated by Django 2.1.4 on 2020-01-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20200108_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='is_systemwide',
            field=models.BooleanField(default=False),
        ),
    ]
