# Generated by Django 2.1.4 on 2020-01-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_parameter_is_systemwide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries_meta',
            name='upload_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timeseries_meta', to='taskmeta.CeleryTask'),
        ),
    ]
