# Generated by Django 2.1.4 on 2020-02-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200125_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='available_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
