# Generated by Django 2.1.4 on 2020-02-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_location_available_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstract_tech',
            options={'ordering': ['id'], 'verbose_name_plural': '[Admin] Abstract Technologies'},
        ),
        migrations.AlterModelOptions(
            name='loc_tech',
            options={'ordering': ['technology__abstract_tech__name', 'technology__pretty_name', 'location_1', 'location_2'], 'verbose_name_plural': '[3] Location Technologies'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['pretty_name'], 'verbose_name_plural': '[1] Locations'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name', '-snapshot_version'], 'verbose_name_plural': '[0] Models'},
        ),
        migrations.AlterModelOptions(
            name='model_comment',
            options={'ordering': ['-created'], 'verbose_name_plural': '[0] Model Comments'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['year', '-created'], 'verbose_name_plural': '[5] Runs'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['name'], 'verbose_name_plural': '[4] Scenarios'},
        ),
        migrations.AlterModelOptions(
            name='scenario_param',
            options={'ordering': ['run_parameter__pretty_name', 'year', 'id'], 'verbose_name_plural': '[4] Scenario Parameters'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['pretty_name'], 'verbose_name_plural': '[2] Technologies'},
        ),
        migrations.AlterModelOptions(
            name='timeseries_meta',
            options={'ordering': ['-is_uploading', '-created'], 'verbose_name_plural': '[3] Timeseries Meta'},
        ),
        migrations.AlterModelOptions(
            name='user_file',
            options={'ordering': ['-created'], 'verbose_name_plural': '[0] User File Uploads'},
        ),
        migrations.AddField(
            model_name='parameter',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
    ]
