# Generated by Django 2.1.4 on 2020-02-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_parameter_is_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
