# Generated by Django 2.1.4 on 2020-03-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_run_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract_tech',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract_tech',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract_tech',
            name='pretty_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='abstract_tech',
            name='pretty_name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='help_guide',
            name='html_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='help_guide',
            name='html_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='category_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='category_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='pretty_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='pretty_name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='pretty_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='pretty_name_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
