# Generated by Django 2.1.4 on 2020-04-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20200318_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='timezone',
            field=models.TextField(default='UTC'),
        ),
    ]
