# Generated by Django 2.2.12 on 2020-09-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_user_profile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='power_units',
        ),
        migrations.RemoveField(
            model_name='model',
            name='temporal_resolution',
        ),
    ]
