# Generated by Django 2.2.12 on 2020-09-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20200908_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='loc_tech_param',
            name='raw_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tech_param',
            name='raw_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
