# Generated by Django 2.2.13 on 2020-12-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_run_outputs_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
