# Generated by Django 2.2.13 on 2021-03-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_run_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_uploading',
            field=models.BooleanField(default=False),
        ),
    ]
