# Generated by Rob Spencer on 2021-05-06
from django.db import migrations


def forward(apps, schema_editor):
    params = apps.get_model('api', 'Tech_Param').objects.filter(
        parameter__units__contains='%')
    for p in params:
        try:
            value = str(float(p.value) * 100)
            raw_value = p.raw_value
            if p.raw_value is not None:
                try:
                    raw_value = str(float(raw_value.replace(',', '')) * 100)
                except Exception:
                    if '%' not in raw_value:
                        raw_value = raw_value + ' * 100'
            p.value = value
            p.raw_value = raw_value
            p.save()
        except Exception:
            pass
    params = apps.get_model('api', 'Loc_Tech_Param').objects.filter(
        parameter__units__contains='%')
    for p in params:
        try:
            value = str(float(p.value) * 100)
            raw_value = p.raw_value
            if p.raw_value is not None:
                try:
                    raw_value = str(float(raw_value.replace(',', '')) * 100)
                except Exception:
                    if '%' not in raw_value:
                        raw_value = raw_value + ' * 100'
            p.value = value
            p.raw_value = raw_value
            p.save()
        except Exception:
            pass


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210324_1629'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
