# Generated by Django 2.2.24 on 2021-07-28 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_percent_param_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='is_expansion',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='is_linear',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='is_expansion',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='is_linear',
        ),
    ]
