# Generated by Django 2.2.24 on 2021-07-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20210728_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='calliope_066_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='calliope_066_upgraded',
            field=models.BooleanField(default=False),
        ),
    ]
