# Generated by Django 2.2.24 on 2021-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_add_all_scenario_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='cluster',
            field=models.BooleanField(default=True),
        ),
    ]
