# Generated by Django 2.2.24 on 2021-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_run_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
