# Generated by Django 3.2.13 on 2022-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_run_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='timestep',
            field=models.TextField(default='1H'),
        ),
    ]
