# Generated by Django 3.2.15 on 2022-08-16 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmeta', '0004_alter_batchtask_options'),
        ('api', '0055_auto_20220605_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='batch_job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='taskmeta.batchtask'),
        ),
    ]
