# Generated by Django 3.2.15 on 2022-10-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_run_batch_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='group',
            field=models.TextField(blank=True),
        ),
    ]
