# Generated by Django 3.2.15 on 2022-11-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_run_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
