# Generated by Django 3.2.16 on 2023-01-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_run_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract_tech',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract_tech',
            name='pretty_name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='help_guide',
            name='html_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='category_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='pretty_name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='pretty_name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
