# Generated by Django 3.2.15 on 2023-04-21 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmeta', '0004_alter_batchtask_options'),
        ('api', '0060_auto_20230414_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('inputs', models.JSONField(blank=True, null=True)),
                ('output_path', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(default=None, editable=False, null=True)),
                ('job_task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_meta', to='taskmeta.celerytask')),
            ],
            options={
                'verbose_name_plural': 'Job Meta',
                'db_table': 'job_meta',
                'ordering': ['-created'],
            },
        ),
    ]
