# Generated by Django 3.2.20 on 2023-08-10 00:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmeta', '0004_alter_batchtask_options'),
        ('api', '0060_auto_20230629_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='loc_tech',
            name='template_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loc_tech',
            name='template_type_loc_tech_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='template_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='template_type_loc_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='template_type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='template_type_tech_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run_parameter',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='Job_Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('inputs', models.JSONField(blank=True, null=True)),
                ('outputs', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(default=None, editable=False, null=True)),
                ('job_task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_meta', to='taskmeta.celerytask')),
            ],
            options={
                'verbose_name_plural': '[0] Job Meta',
                'db_table': 'job_meta',
                'ordering': ['-created'],
            },
        ),
    ]
