# Generated by Django 3.2.20 on 2023-09-16 04:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20230810_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='loc_tech_param',
            name='flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
        migrations.AddField(
            model_name='tech_param',
            name='flags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=None),
        ),
    ]
