# Generated by Django 3.2.18 on 2023-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_job_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_meta',
            options={'ordering': ['-created'], 'verbose_name_plural': '[0] Job Meta'},
        ),
        migrations.RemoveField(
            model_name='job_meta',
            name='output_path',
        ),
        migrations.AddField(
            model_name='job_meta',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_meta',
            name='outputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
