# Generated by Django 3.2.15 on 2023-08-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20230629_1601'),
        ('api', '0062_auto_20230428_1836'),
    ]

    operations = [
    ]
