# Generated by Django 3.2.20 on 2023-10-12 22:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20230916_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.model'),
        ),
    ]
