# Generated by Django 3.2.20 on 2023-11-01 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_carrier_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, null=True, size=None),
        ),
    ]
