# Generated by Django 3.2.25 on 2024-04-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_parameter_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeenvironment',
            name='solver',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
