# Generated by Django 3.2.25 on 2024-04-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_computeenvironment_solver'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRateLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('user_requests', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': '[Admin] Request Rate Limit',
                'verbose_name_plural': '[Admin] Request Rate Limits',
                'db_table': 'request_rate_limit',
            },
        ),
    ]
