# Generated by Django 3.2.25 on 2024-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_computeenvironment_solver'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_user',
            name='role',
            field=models.CharField(default='contributor', max_length=200),
        ),
    ]
