# Generated by Django 3.2.25 on 2024-06-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_requestratelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_options',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='tab',
            field=models.TextField(blank=True, null=True),
        ),
    ]
