# Generated by Django 3.2.25 on 2024-04-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_run_parameter_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run_parameter',
            name='tab',
            field=models.TextField(blank=True, null=True),
        ),
    ]
