# Generated by Django 3.2.25 on 2024-07-03 02:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20240613_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pretty_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('where', models.CharField(max_length=500)),
                ('equations', models.JSONField(blank=True, null=True)),
                ('slices', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '[Admin] Group Constraints',
                'db_table': 'group_constraint',
            },
        ),
        migrations.RenameField(
            model_name='loc_tech_param',
            old_name='year',
            new_name='build_year',
        ),
        migrations.RenameField(
            model_name='tech_param',
            old_name='year',
            new_name='build_year',
        ),
        migrations.AddField(
            model_name='loc_tech_param',
            name='build_year_offset',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='dim',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='index',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='dim',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='index',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tech_param',
            name='build_year_offset',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
