# Generated by Django 3.2.25 on 2024-05-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_run_parameter_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_options',
            field=models.JSONField(default=None, null=True),
        ),
    ]
