# Generated by Django 3.2.25 on 2024-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_run_parameter_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario_param',
            name='tab',
            field=models.TextField(default=''),
        ),
    ]
