# Generated by Django 3.2.25 on 2024-08-02 22:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20240704_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='dim',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='index',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, null=True, size=None),
        ),
    ]
