# Generated by Django 4.2.16 on 2024-10-11 20:16

import api.models.engage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_run_parameter_default_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computeenvironment',
            name='solver',
        ),
        migrations.AddField(
            model_name='computeenvironment',
            name='solvers',
            field=models.JSONField(default=api.models.engage.default_solvers),
        ),
    ]
