# Generated by Django 4.2.15 on 2025-01-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_loc_tech_param_dim_loc_tech_param_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run_parameter',
            name='default_value',
            field=models.CharField(max_length=5000),
        ),
    ]
