# Generated by Django 4.2.16 on 2025-07-07 07:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_alter_run_parameter_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='build_operate_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='mode',
            field=models.CharField(default='plan', max_length=20),
        ),
        migrations.AddField(
            model_name='run',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.run'),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='mode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
