# Generated by Django 4.2.16 on 2025-07-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_run_build_operate_run_run_mode_run_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loc_tech_param',
            name='piecewise_dim',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tech_param',
            name='piecewise_dim',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
