# Generated by Django 4.2.16 on 2025-09-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_loc_tech_param_piecewise_dim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run_parameter',
            name='default_value',
            field=models.CharField(max_length=10000),
        ),
    ]
