# Generated by Django 4.2.16 on 2026-06-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_run_parameter_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract_tech',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract_tech',
            name='pretty_name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group_constraint',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group_constraint',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group_constraint',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group_constraint',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group_constraint',
            name='pretty_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group_constraint',
            name='pretty_name_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group_constraint',
            name='pretty_name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group_constraint',
            name='pretty_name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='help_guide',
            name='html_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='category_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='pretty_name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='description_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run_parameter',
            name='pretty_name_pt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
