from django.urls import path
from .views import configuration as configuration_views
from .views import engage as engage_views
from .views import outputs as outputs_views
from .component_views import configuration as configuration_component_views
from .component_views import outputs as outputs_component_views

urlpatterns = [
    # Configuration Component Views
    path('component/all_tech_params/',
         configuration_component_views.all_tech_params,
         name='all_tech_params'),
    path('component/all_loc_tech_params/',
         configuration_component_views.all_loc_tech_params,
         name='all_loc_tech_params'),
    path('component/all_loc_techs/',
         configuration_component_views.all_loc_techs,
         name='all_loc_techs'),
    path('component/group_constraint_options/',
         configuration_component_views.group_constraint_options,
         name='group_constraint_options'),
    path('component/location_coordinates/',
         configuration_component_views.location_coordinates,
         name='location_coordinates'),
    path('component/timeseries_view/',
         configuration_component_views.timeseries_view,
         name='timeseries_view'),
    path('component/timeseries_new/',
         configuration_component_views.timeseries_new,
         name='timeseries_new'),
    path('component/timeseries_content/',
         configuration_component_views.timeseries_content,
         name='timeseries_content'),
    path('component/scenario/',
         configuration_component_views.scenario,
         name='scenario'),

    # Outputs Component Views
    path('component/run_dashboard/',
         outputs_component_views.run_dashboard,
         name='run_dashboard'),
    path('component/add_run_precheck/',
         outputs_component_views.add_run_precheck,
         name='add_run_precheck'),
    path('component/show_logs/',
         outputs_component_views.show_logs,
         name='show_logs'),
    path('component/plot_outputs/',
         outputs_component_views.plot_outputs,
         name='plot_outputs'),
    path('component/map_outputs/',
         outputs_component_views.map_outputs,
         name='map_outputs'),

    # Configuration Views
    path('<model_uuid>/model/',
         configuration_views.model_view,
         name='model'),
    path('<model_uuid>/parameters/<parameter_name>/',
         configuration_views.parameters_view,
         name='parameters'),
    path('<model_uuid>/timeseries/',
         configuration_views.timeseries_view,
         name='timeseries'),
    path('<model_uuid>/timeseries_table/',
         configuration_views.timeseries_table,
         name='timeseries_table'),
    path('<model_uuid>/loc_techs/',
         configuration_views.loc_techs_view,
         name='loc_techs'),
    path('<model_uuid>/locations/',
         configuration_views.locations_view,
         name='locations'),
    path('<model_uuid>/technologies/',
         configuration_views.technologies_view,
         name='technologies'),
    path('<model_uuid>/add_technologies/',
         configuration_views.add_technologies_view,
         name='add_technologies'),
    path('<model_uuid>/scenarios/',
         configuration_views.scenarios_view,
         name='scenarios'),
    path('<model_uuid>/add_scenarios/',
         configuration_views.add_scenarios_view,
         name='add_scenarios'),
    path('<model_uuid>/carriers/',
         configuration_views.carriers_view,
         name='carriers'),
    path('<model_uuid>/model_flags/',
         configuration_views.model_flags_view,
         name='model_flags'),

    # Admin tables
    path('admin/group_constraints/',
         configuration_views.admin_group_constraints,
         name='group_constraints'),

    # Outputs Views
    path('<model_uuid>/runs/',
         outputs_views.runs_view,
         name='runs'),
    path('<model_uuid>/add_runs/<scenario_id>/',
         outputs_views.add_runs_view,
         name='add_runs'),
    path('<model_uuid>/<run_id>/map_viz/',
         outputs_views.map_viz_view,
         name='map_viz'),

    # Engage Views
    path('share/',
         engage_views.share_view,
         name='settings'),
    path('admin/login/',
         engage_views.admin_login_view,
         name="admin"),
    path('',
         engage_views.home_view,
         name='home')
]
