# Generated by Django 2.1.4 on 2019-09-06 19:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, max_length=36, null=True)),
                ('status', models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=50)),
                ('date_start', models.DateTimeField(editable=False, null=True)),
                ('date_done', models.DateTimeField(editable=False, null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True)),
                ('traceback', models.TextField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': '[Admin] Celery Tasks',
                'db_table': 'celery_task',
            },
        ),
    ]
