# Generated by Django 3.2.15 on 2022-08-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmeta', '0003_batchtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtask',
            options={'verbose_name_plural': '[Admin] Batch Tasks'},
        ),
    ]
